CREATE DATABASE PFINALP2
GO
USE PFINALP2
GO

CREATE TABLE USUARIOS
(
ID_USUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
CODUSUARIO AS ('US' + RIGHT ('00' + CONVERT ([NVARCHAR], [ID_USUARIO]),(2))),
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(100),
FECHANACIMIENTO DATETIME,
TIPOUSUARIO VARCHAR(20),
USERPASSWORD NVARCHAR(100)
)
GO

CREATE TABLE VISITANTES 
(
ID_VISITANTE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(100),
CARRERA VARCHAR(100),
EDIFICIO INT FOREIGN KEY REFERENCES EDIFICIO(ID_EDIFICIO),
HORAENTRADA DATETIME,
HORASALIDA DATETIME,
MOTIVOVISITA VARCHAR(200),
ID_AULA NVARCHAR(20) FOREIGN KEY REFERENCES AULA(ID_AULA)
)
GO

CREATE TABLE AULA
(
ID_AULA NVARCHAR(20) PRIMARY KEY,
EDIFICIO INT FOREIGN KEY REFERENCES EDIFICIO(ID_EDIFICIO)
)
GO


CREATE TABLE EDIFICIO
(
ID_EDIFICIO INT PRIMARY KEY,
DESCRIPCION VARCHAR(100)
)
GO

/*STORE PROCEDIRE DE LA TABLA EDIFICIO*/
/*INSERTAR*/
CREATE PROC SP_INSERTAREDIFICIO
@ID_EDIFICIO INT,
@DESCRIPCION VARCHAR(100)
AS
INSERT INTO EDIFICIO VALUES
(@ID_EDIFICIO, @DESCRIPCION)
GO

/*LISTAR EDIFICIOS*/
CREATE PROC SP_LISTAREDIFICIOS
@ID_EDIFICIO INT
AS
SELECT * FROM EDIFICIO 
WHERE ID_EDIFICIO = @ID_EDIFICIO
GO


CREATE PROC SP_LISTAREDIFICIOSG
AS
SELECT * FROM EDIFICIO 
GO

/*EDITAR EDIFICIOS*/
CREATE PROC SP_EDITAREDIFICIOS
@SELECCION INT,
@NEW_ID INT,
@DESCRIPCION VARCHAR(100)
AS
UPDATE EDIFICIO SET ID_EDIFICIO=@NEW_ID, DESCRIPCION = @DESCRIPCION
WHERE ID_EDIFICIO = @SELECCION
GO

/*STORED PROCEDURES DE LA TABLA USUARIOS */
CREATE PROC SP_INSERTARUSUARIO
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(100),
@FECHANACIMIENTO DATETIME,
@TIPOUSUARIO VARCHAR(20),
@USERPASSWORD NVARCHAR(100)
AS
INSERT INTO USUARIOS VALUES
(@NOMBRE, @APELLIDO, @FECHANACIMIENTO, 
@TIPOUSUARIO, @USERPASSWORD)
GO
/*Actualizar usuario*/
CREATE PROC SP_ACTUALIZARUSUARIO
@CODUSUARIO NVARCHAR(100),
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(100),
@FECHANACIMIENTO DATETIME,
@TIPOUSUARIO VARCHAR(20),
@USERPASSWORD NVARCHAR(100)
AS
UPDATE USUARIOS SET NOMBRE=@NOMBRE, APELLIDO=@APELLIDO,
FECHANACIMIENTO=@FECHANACIMIENTO, TIPOUSUARIO=@TIPOUSUARIO,
USERPASSWORD=@USERPASSWORD WHERE CODUSUARIO=@CODUSUARIO
GO
/*Buscar usuario por codigo*/
CREATE PROC SP_BUSCARUSUARIO
@CODUSUARIO NVARCHAR(100)
AS
SELECT * FROM USUARIOS WHERE CODUSUARIO=@CODUSUARIO
GO

/*Buscar usuario por nombre*/
CREATE PROC SP_BUSCARUSUARIOPPORNOMBRE
@BUSCAR VARCHAR(20)
AS
SELECT * FROM USUARIOS
WHERE NOMBRE LIKE @BUSCAR + '%'
GO

/*Eliminar usuario*/
CREATE PROC SP_ELIMINARUSUARIO
@CODUSUARIO NVARCHAR(100)
AS
DELETE USUARIOS WHERE CODUSUARIO=@CODUSUARIO
GO
/*Login usuario*/
CREATE PROC SP_LOGIN
@CODUSUARIO NVARCHAR(100),
@USERPASSWORD NVARCHAR(100)
AS
SELECT * FROM USUARIOS
WHERE CODUSUARIO = @CODUSUARIO AND
USERPASSWORD = @USERPASSWORD
GO

/*STORED PROCEDURES DE LA TABLA VISITANTES*/
/*Insertar visitantes*/
CREATE PROC SP_INSERTARVISITANTE
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(100),
@CARRERA VARCHAR(100),
@EDIFICIO INT,
@HORASALIDA DATETIME,
@MOTIVOVISITA VARCHAR(200),
@ID_AULA NVARCHAR(20) 
AS
INSERT INTO VISITANTES VALUES
(
@NOMBRE, @APELLIDO, @CARRERA, @EDIFICIO, GETDATE(),@HORASALIDA,
@MOTIVOVISITA,@ID_AULA
)
GO

/*Buscar visitantes por nombre*/
CREATE PROC SP_BUSCARVISITANTE
@BUSCAR VARCHAR(50)
AS
SELECT * FROM VISITANTES
WHERE NOMBRE LIKE @BUSCAR + '%'
GO

/*Buscar visitas por edificio*/
CREATE PROC SP_BUSCARVISPOREDIFICIO
@BUSCAR INT
AS
SELECT * FROM VISITANTES
WHERE EDIFICIO=@BUSCAR
GO


/*Consultar Visitas por los edificios segun el edificio*/
CREATE PROC SP_BUSCARVISTITANTESNE
@NOMBRE VARCHAR(50),
@EDIFICIO INT
AS
SELECT * FROM VISITANTES
WHERE NOMBRE=@NOMBRE AND EDIFICIO=@EDIFICIO
GO

/*LISTAR VISITANTES*/
CREATE PROC SP_LISTARVISITANTES
AS
SELECT * FROM VISITANTES
GO


/*STORE PROCEDURE DE AULAS*/
CREATE PROC SP_INSERTARAULA
@ID_AULA NVARCHAR(20),
@EDIFICIO INT
AS
INSERT INTO AULA VALUES
(@ID_AULA, @EDIFICIO)
GO

/*BUSCAR AULA POR ID*/
CREATE PROC SP_BUSCARAULA
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM AULA
WHERE ID_AULA LIKE @BUSCAR + '%'
GO

/*BUSCAR AULAS POR EDIFICIOS*/
CREATE PROC SP_BUSCARAUPEDI
@EDIFICIO INT
AS
SELECT * FROM AULA WHERE EDIFICIO=@EDIFICIO
GO

/*ELIMINAR AULA*/
CREATE PROC SP_ELIMINARAULA
@ID_AULA NVARCHAR(20)
AS
DELETE AULA WHERE ID_AULA = @ID_AULA
GO

/*ACTUALIZAR AULA*/
CREATE PROC SP_ACTUALIZARAULA
@ID_ACTAULA NVARCHAR(20),
@ID_AULA NVARCHAR(20),
@EDIFICIO INT
AS
UPDATE AULA SET ID_AULA=@ID_AULA, EDIFICIO=@EDIFICIO
WHERE ID_AULA=@ID_ACTAULA
GO



